apiVersion: v1
kind: Service
metadata:
  name: client-deployment
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: binance
        image: darenson/binance
        imagePullPolicy: Never
        ports:
        - containerPort: 5000